<a href="https://colab.research.google.com/github/AndresMontesDeOca/GdP/blob/master/Estadistica_TP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabajo Practico #2

Nombre: Jose Andres Montes de Oca

Código: a2532

In [8]:
# Librerias

import sympy as sp
import numpy as np

## Pregunta 1

1. Una variable aleatoria discreta $X$ puede tomar los valores 0, 1, 2 y 3. Las probabilidades para cada valor posible están dadas por la siguiente tabla:

$$
\begin{array}{|c|c|c|c|c|}
\hline
X & 0 & 1 & 2 & 3 \\
\hline
p & \frac{3\theta}{3} & \frac{6\theta}{3} & \frac{1-3\theta}{3} & \frac{2(1-3\theta)}{3} \\
\hline
\end{array}
$$

Si experimentalmente se obtienen los siguientes datos:
$(3, 3, 2, 1, 2, 3, 3, 0, 1, 1)$,
determine el valor de $\theta$ usando el método de máxima verosimilitud.

In [23]:


# Parámetro a estimar
theta = sp.Symbol('theta', positive=True)

# Datos
datos = [3, 3, 2, 1, 2, 3, 3, 0, 1, 1]

# Conteo de frecuencias
n0 = datos.count(0)
n1 = datos.count(1)
n2 = datos.count(2)
n3 = datos.count(3)

# Probabilidades
p0 = (3 * theta) / 3
p1 = (6 * theta) / 3
p2 = (1 - 3 * theta) / 3
p3 = 2 * (1 - 3 * theta) / 3

# Multiplicamos la probabilidad de cada suceso elevada a la cantidad de veces que ocurrio
L = (p0**n0) * (p1**n1) * (p2**n2) * (p3**n3)
print(f"Función de Verosimilitud (theta):\n{sp.simplify(L)}\n")

# expand_log ayuda a separar los productos en sumas para facilitar la derivada
l_theta = sp.expand_log(sp.log(L), force=True)

# Derivada de la Log-verosimilitud respecto a theta
dl_dtheta = sp.diff(l_theta, theta)
print(f"Derivada de la Log-Verosimilitud l'(theta) igualada a 0:\n0 = {sp.simplify(dl_dtheta)}\n")

# Resolver la ecuación (encontrar la raíz de la derivada)
theta_mle = sp.solve(dl_dtheta, theta)[0]

print(f"El Estimador de Máxima Verosimilitud para theta es: {theta_mle}")

Función de Verosimilitud (theta):
128*theta**4*(3*theta - 1)**6/729

Derivada de la Log-Verosimilitud l'(theta) igualada a 0:
0 = 2*(15*theta - 2)/(theta*(3*theta - 1))

El Estimador de Máxima Verosimilitud para theta es: 2/15


## Pregunta 2
Se pretende estimar los valores de producción $Y$ (en miles de toneladas) de cierto material, en función del tiempo transcurrido $X$ (en meses) usando los valores de la tabla:

$$
\begin{array}{|c|c|}
\hline
X & Y \\
\hline
2 & 3 \\
\hline
8 & 51 \\
\hline
14 & 173 \\
\hline
15 & 320 \\
\hline
21 & 576 \\
\hline
\end{array}
$$

Se plantea un modelo de la forma $Y = a + bx + cx^2$. Encontrar los estimadores de mínimos cuadrados para $a$, $b$ y $c$ en este modelo.

In [6]:


# 1. Definimos los vectores de datos empíricos
X_datos = np.array([2, 8, 14, 15, 21])
Y_datos = np.array([3, 51, 173, 320, 576])

# 2. Construimos la matriz de diseño X para el modelo Y = a + bX + cX^2
# Columna 1: unos (x^0, acompaña al parámetro 'a')
# Columna 2: valores de X (x^1, acompaña al parámetro 'b')
# Columna 3: valores de X al cuadrado (x^2, acompaña al parámetro 'c')
matriz_X = np.column_stack((np.ones(len(X_datos)), X_datos, X_datos**2))

print("Matriz de diseño X:")
print(matriz_X)

# 3. Aplicamos el método de Mínimos Cuadrados mediante Ecuaciones Normales
# Fórmula: beta = (X^T * X)^-1 * X^T * Y
X_T = matriz_X.T  # Transpuesta de X

# Calculamos (X^T * X)
XT_X = X_T.dot(matriz_X)

# Calculamos la inversa de (X^T * X)
XT_X_inv = np.linalg.inv(XT_X)

# Multiplicamos por X^T y luego por Y
beta = XT_X_inv.dot(X_T).dot(Y_datos)

# 4. Extraemos los estimadores
a, b, c = beta

print("\n--- Resultados de Mínimos Cuadrados ---")
print(f"Estimador a (intercepto): {a:.4f}")
print(f"Estimador b (lineal):     {b:.4f}")
print(f"Estimador c (cuadrático): {c:.4f}")

print(f"\nEcuación del modelo estimado:")
print(f"Y = {a:.4f} + {b:.4f}X + {c:.4f}X^2")


Matriz de diseño X:
[[  1.   2.   4.]
 [  1.   8.  64.]
 [  1.  14. 196.]
 [  1.  15. 225.]
 [  1.  21. 441.]]

--- Resultados de Mínimos Cuadrados ---
Estimador a (intercepto): 12.3004
Estimador b (lineal):     -8.8280
Estimador c (cuadrático): 1.7109

Ecuación del modelo estimado:
Y = 12.3004 + -8.8280X + 1.7109X^2


## Pregunta 3
Don Francisco tiene 8 clientes a los que les ha vendido mercancías a crédito y, de ellos, 1 están en mora con el pago prometido. Matías, teniendo en cuenta la información disponible, considera que puede modelar el porcentaje $p$ de morosidad según una distribución $\mathcal{B}(1,4)$. Para determinar los parámetros $\alpha$ y $\beta$, decide usar inferencia bayesiana. Con esto, pretende explicarle a Don Francisco, cómo será el comportamiento de pago de sus clientes a crédito. Determinen la distribución a posteriori del parámetro $p$ de porcentaje de morosidad ($\alpha$ y $\beta$). Determinar su media y su varianza.

In [7]:
# 1. Parámetros de la distribución a priori: Beta(alpha_prior, beta_prior)
alpha_prior = 1
beta_prior = 4

print(f"Distribución a Priori: Beta({alpha_prior}, {beta_prior})")

# 2. Datos observados (modelo Binomial)
n = 8  # Número total de clientes
k = 1  # Número de clientes en mora

print(f"Datos observados: n={n}, k={k} (éxitos/mora)")

# 3. Parámetros de la distribución a posteriori: Beta(alpha_post, beta_post)
# Usando la propiedad de conjugación de la familia Beta-Binomial
alpha_post = alpha_prior + k
beta_post = beta_prior + n - k

print(f"\nDistribución a Posteriori: Beta({alpha_post}, {beta_post})")

# 4. Calcular la media y la varianza de la distribución a posteriori
# Fórmulas para una distribución Beta(a, b):
# Media = a / (a + b)
# Varianza = (a * b) / [ (a + b)^2 * (a + b + 1) ]

media_post = alpha_post / (alpha_post + beta_post)

# Numerador y denominador de la varianza para mayor claridad
num_var = alpha_post * beta_post
den_var = ((alpha_post + beta_post)**2) * (alpha_post + beta_post + 1)
varianza_post = num_var / den_var

print("\n--- Resultados Finales ---")
print(f"Parámetros Posteriori: alpha = {alpha_post}, beta = {beta_post}")
print(f"Media esperada del porcentaje de morosidad (p): {media_post:.4f} (aprox {media_post*100:.2f}%)")
print(f"Varianza de p: {varianza_post:.6f}")


Distribución a Priori: Beta(1, 4)
Datos observados: n=8, k=1 (éxitos/mora)

Distribución a Posteriori: Beta(2, 11)

--- Resultados Finales ---
Parámetros Posteriori: alpha = 2, beta = 11
Media esperada del porcentaje de morosidad (p): 0.1538 (aprox 15.38%)
Varianza de p: 0.009298
